# -*- coding: utf-8 -*-
"""FREQ_DIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMCVEbjoLYtxE5I4xwNxiT7aGnQ5AnxG
"""

# import libraries
import pandas as pd

import matplotlib.pyplot as plt

import string
import re

import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

!pip install leia-br
from LeIA import SentimentIntensityAnalyzer

nltk.download('all')
nltk.download('stopwords')

from wordcloud import wordcloud

from google.colab import files
import pandas as pd

# Upload do arquivo CSV
uploaded = files.upload()

# Lê o arquivo CSV (substitua 'nome_do_arquivo.csv' pelo nome do seu arquivo)
file_name = next(iter(uploaded)) # Get the uploaded filename
df = pd.read_excel(file_name) # Changed to pd.read_excel assuming .xlsx format

# Mostra as primeiras linhas
df.head()

# Definir stopwords completas (padrão + gírias)
stopwords_nltk = set(stopwords.words('portuguese'))
girias = {'vc', 'vcs', 'tá', 'bora', 'mano', 'kkk', 'né', 'vlw', 'eita', 'uai', 'pra', 'q', 'td', 'vai', 'anos' 'blz', 'ta', 'china'}
# Incluí 'china' para remover a própria palavra, se desejar
stopwords_final = stopwords_nltk.union(girias)

# Função de pré-processamento que usa as stopwords completas
def pre_processamento(texto):
    if pd.isna(texto):
        return ""

    # Extrai apenas palavras (incluindo acentos) e converte para minúsculas
    palavras = re.findall(r'\b[A-zÀ-úü]+\b', texto.lower())

    # Remove stopwords
    palavras_filtradas = [p for p in palavras if p not in stopwords_final]
    return " ".join(palavras_filtradas)

print(df.columns.tolist())

coluna_texto = 'Tweet_Content'
df['texto_limpo'] = df[coluna_texto].apply(pre_processamento)

# Filtrar linhas que contenham a palavra "China" (case insensitive)
df_china = df[df[coluna_texto].str.contains('China', case=False, na=False)].copy()
print(f"Tweets sobre China: {len(df_china)}")

df.head()

textos_china = " ".join(df_china['texto_limpo'])

# Tokenizar (as palavras já estão separadas por espaço)
palavras_china = textos_china.split()

# Se quiser excluir a própria palavra 'china' (caso não tenha sido removida pelas stopwords)
palavras_china = [p for p in palavras_china if p != 'china']

# Calcular frequência
from nltk.probability import FreqDist
freq_dist_china = FreqDist(palavras_china)

# Exibir as 20 mais comuns
print("Top 15 palavras em tweets sobre China:")
for palavra, freq in freq_dist_china.most_common(15):
    print(f"{palavra}: {freq}")

# Plotar gráfico
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))
freq_dist_china.plot(15, title='Palavras mais associadas ao termo "China"-Janeiro 2026', cumulative=False)
plt.show()

# Gerar nuvem de palavras a partir dos textos sobre China
texto_unido = " ".join(df_china['texto_limpo'])  # use a coluna limpa
wordcloud_obj = wordcloud.WordCloud(width=400, height=400,
                      background_color='white',
                      max_words=200,
                      stopwords=stopwords_final,  # já tem suas stopwords
                      colormap='cubehelix_r').generate(texto_unido)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud_obj, interpolation='bilinear')
plt.axis('off')
plt.title('Nuvem de palavras - Tweets sobre China')
plt.show()